//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodysShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int InventoryID { get; set; }
        public string ItemDescription { get; set; }
        public string Date { get; set; }
        public string Vendor { get; set; }
        public string ItemName { get; set; }
        public string ItemCost { get; set; }
        public string ItemMarkUp { get; set; }
        public string Sku { get; set; }
        public string InStock { get; set; }
    }
}
