//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodysShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrekerIntake
    {
        public int Id { get; set; }
        public string Totaled { get; set; }
        public string Parts { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Vin { get; set; }
        public string Location { get; set; }
    }
}
